--
-- PostgreSQL database dump
--

-- Dumped from database version 14.2
-- Dumped by pg_dump version 14.2

-- Started on 2022-05-19 13:40:21

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 211 (class 1259 OID 16747)
-- Name: AuditLogs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AuditLogs" (
    "Id" integer NOT NULL,
    "UserId" text,
    "Type" text NOT NULL,
    "TableName" text NOT NULL,
    "DateTime" timestamp with time zone NOT NULL,
    "OldValues" text,
    "NewValues" text NOT NULL,
    "AffectedColumns" text,
    "PrimaryKey" text NOT NULL
);


ALTER TABLE public."AuditLogs" OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 16746)
-- Name: AuditLogs_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AuditLogs" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AuditLogs_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 16741)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 16763)
-- Name: ejercicios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ejercicios (
    id integer NOT NULL,
    enunciado character varying NOT NULL,
    id_libro integer NOT NULL
);


ALTER TABLE public.ejercicios OWNER TO postgres;

--
-- TOC entry 214 (class 1259 OID 16762)
-- Name: ejercicios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ejercicios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ejercicios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 16755)
-- Name: libros; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.libros (
    id integer NOT NULL,
    titulo character varying NOT NULL
);


ALTER TABLE public.libros OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 16754)
-- Name: libros_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.libros ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.libros_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16775)
-- Name: respuesta; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.respuesta (
    id_ejercicio integer NOT NULL,
    id_usuario integer NOT NULL,
    valor character varying NOT NULL
);


ALTER TABLE public.respuesta OWNER TO postgres;

--
-- TOC entry 3185 (class 2606 OID 16753)
-- Name: AuditLogs PK_AuditLogs; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AuditLogs"
    ADD CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id");


--
-- TOC entry 3183 (class 2606 OID 16745)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 3190 (class 2606 OID 16769)
-- Name: ejercicios pk_ejercicio; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ejercicios
    ADD CONSTRAINT pk_ejercicio PRIMARY KEY (id);


--
-- TOC entry 3192 (class 2606 OID 16781)
-- Name: respuesta pk_ejercicio_usuario; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.respuesta
    ADD CONSTRAINT pk_ejercicio_usuario PRIMARY KEY (id_ejercicio, id_usuario);


--
-- TOC entry 3187 (class 2606 OID 16761)
-- Name: libros pk_libro; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.libros
    ADD CONSTRAINT pk_libro PRIMARY KEY (id);


--
-- TOC entry 3188 (class 1259 OID 16787)
-- Name: IX_ejercicios_id_libro; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_ejercicios_id_libro" ON public.ejercicios USING btree (id_libro);


--
-- TOC entry 3194 (class 2606 OID 16782)
-- Name: respuesta FK_respuesta_ejercicios_id_ejercicio; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.respuesta
    ADD CONSTRAINT "FK_respuesta_ejercicios_id_ejercicio" FOREIGN KEY (id_ejercicio) REFERENCES public.ejercicios(id);


--
-- TOC entry 3193 (class 2606 OID 16770)
-- Name: ejercicios fk_libro; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ejercicios
    ADD CONSTRAINT fk_libro FOREIGN KEY (id_libro) REFERENCES public.libros(id) ON DELETE CASCADE;


-- Completed on 2022-05-19 13:40:22

--
-- PostgreSQL database dump complete
--

